### ISSUE TITLE
ERROR was detected: assert($nameString instanceof String)_ ; "Define()"

### ISSUE THREAD

**Issue by DarkSynx** [phpDocumentor/phpDocumentor#3296]
**ALERT     [app]   Unable to parse file _"modules/Modules_gestionnaire.php", an error was detected: assert($nameString instanceof String_)_**
![image](https://user-images.githubusercontent.com/9467611/181191656-d851652b-7508-4f94-9624-85e0a5a76e64.png)

option -vvv

```
07:40:11 NOTICE    [app] Parsing modules/Modules_gestionnaire.php
07:40:11 INFO      [app] Starting to parse file: modules/Modules_gestionnaire.php
07:40:11 ALERT     [app]   Unable to parse file "modules/Modules_gestionnaire.php", an error was detected: assert($nameString instanceof String_)
07:40:11 NOTICE    [app]   -- Found in phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Define.php at line 128
07:40:11 DEBUG     [app]   #0 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Define.php(128): assert(false, 'assert($nameStr...')
#1 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Define.php(106): phpDocumentor\Reflection\Php\Factory\Define->determineFqsen(Object(PhpParser\Node\Arg))
#2 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php(59): phpDocumentor\Reflection\Php\Factory\Define->doCreate(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\Expression), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#3 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/IfStatement.php(25): phpDocumentor\Reflection\Php\Factory\AbstractFactory->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\Expression), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#4 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Method.php(88): phpDocumentor\Reflection\Php\Factory\IfStatement->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\If_), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#5 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php(59): phpDocumentor\Reflection\Php\Factory\Method->doCreate(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\ClassMethod), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#6 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Class_.php(78): phpDocumentor\Reflection\Php\Factory\AbstractFactory->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\ClassMethod), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#7 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php(59): phpDocumentor\Reflection\Php\Factory\Class_->doCreate(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\Class_), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#8 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Namespace_.php(49): phpDocumentor\Reflection\Php\Factory\AbstractFactory->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\Class_), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#9 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/File.php(135): phpDocumentor\Reflection\Php\Factory\Namespace_->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\Namespace_), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#10 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/File.php(120): phpDocumentor\Reflection\Php\Factory\File->createElements(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Array, Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#11 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/File.php(71): phpDocumentor\Reflection\Php\Factory\File->createFile(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#12 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Parser/Middleware/ReEncodingMiddleware.php(46): phpDocumentor\Reflection\Php\Factory\File->phpDocumentor\Reflection\Php\Factory\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#13 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\ReEncodingMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#14 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Parser/Middleware/ErrorHandlingMiddleware.php(46): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#15 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\ErrorHandlingMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#16 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Parser/Middleware/CacheMiddleware.php(66): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#17 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/cache/Traits/ContractsTrait.php(54): phpDocumentor\Parser\Middleware\CacheMiddleware->phpDocumentor\Parser\Middleware\{closure}(Object(Symfony\Component\Cache\CacheItem), true)
#18 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/cache/Traits/ContractsTrait.php(100): Symfony\Component\Cache\Adapter\AbstractAdapter::Symfony\Component\Cache\Traits\{closure}(Object(Closure), Object(Symfony\Component\Cache\CacheItem), true, Object(phpDocumentor\Parser\Cache\FilesystemAdapter), Object(Closure), NULL)
#19 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/contracts/Cache/CacheTrait.php(72): Symfony\Component\Cache\Adapter\AbstractAdapter->Symfony\Component\Cache\Traits\{closure}(Object(Symfony\Component\Cache\CacheItem), true)
#20 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/cache/Traits/ContractsTrait.php(107): Symfony\Component\Cache\Adapter\AbstractAdapter->contractsGet(Object(phpDocumentor\Parser\Cache\FilesystemAdapter), '13f2d85b7004be8...', Object(Closure), 1, Array, NULL)
#21 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/contracts/Cache/CacheTrait.php(35): Symfony\Component\Cache\Adapter\AbstractAdapter->doGet(Object(phpDocumentor\Parser\Cache\FilesystemAdapter), '13f2d85b7004be8...', Object(Closure), 1, Array)
#22 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Parser/Middleware/CacheMiddleware.php(69): Symfony\Component\Cache\Adapter\AbstractAdapter->get('13f2d85b7004be8...', Object(Closure))
#23 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\CacheMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#24 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Parser/Middleware/EmittingMiddleware.php(38): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#25 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\EmittingMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#26 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Parser/Middleware/StopwatchMiddleware.php(50): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#27 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\StopwatchMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#28 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/File.php(97): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#29 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php(59): phpDocumentor\Reflection\Php\Factory\File->doCreate(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(phpDocumentor\Parser\FlySystemFile), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#30 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php(110): phpDocumentor\Reflection\Php\Factory\AbstractFactory->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(phpDocumentor\Parser\FlySystemFile), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#31 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Parser/Parser.php(205): phpDocumentor\Reflection\Php\ProjectFactory->create('Untitled projec...', Array)
#32 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/Parser/ParseFiles.php(62): phpDocumentor\Parser\Parser->parse(Array)
#33 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php(11): phpDocumentor\Pipeline\Stage\Parser\ParseFiles->__invoke(Object(phpDocumentor\Pipeline\Stage\Parser\Payload))
#34 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php(34): League\Pipeline\FingersCrossedProcessor->process(Object(phpDocumentor\Pipeline\Stage\Parser\Payload), Object(phpDocumentor\Pipeline\Stage\Parser\TransformToParserPayload), Object(phpDocumentor\Pipeline\Stage\Parser\CollectFiles), Object(phpDocumentor\Pipeline\Stage\Cache\GarbageCollectCache), Object(phpDocumentor\Pipeline\Stage\Cache\LoadProjectDescriptorFromCache), Object(phpDocumentor\Pipeline\Stage\Cache\LoadGuidesFromCache), Object(phpDocumentor\Pipeline\Stage\Parser\ParseFiles), Object(phpDocumentor\Pipeline\Stage\Parser\ParseGuides), Object(phpDocumentor\Pipeline\Stage\Cache\StoreProjectDescriptorToCache), Object(phpDocumentor\Pipeline\Stage\Cache\StoreGuidesToCache))
#35 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php(39): League\Pipeline\Pipeline->process(Object(phpDocumentor\Pipeline\Stage\Payload))
#36 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php(11): League\Pipeline\Pipeline->__invoke(Object(phpDocumentor\Pipeline\Stage\Payload))
#37 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php(34): League\Pipeline\FingersCrossedProcessor->process(Object(phpDocumentor\Pipeline\Stage\Payload), Object(League\Pipeline\Pipeline), Object(League\Pipeline\Pipeline), Object(League\Pipeline\Pipeline), Object(League\Pipeline\Pipeline))
#38 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php(39): League\Pipeline\Pipeline->process(Array)
#39 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/src/phpDocumentor/Console/Command/Project/RunCommand.php(290): League\Pipeline\Pipeline->__invoke(Array)
#40 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/console/Command/Command.php(298): phpDocumentor\Console\Command\Project\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/console/Application.php(1033): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(phpDocumentor\Console\Command\Project\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(phpDocumentor\Console\Command\Project\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 phar://C:/Users/synxcinaty/Desktop/PHPdoc/phpDocumentor.phar/bin/phpdoc(43): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#47 C:\Users\synxcinaty\Desktop\PHPdoc\phpDocumentor.phar(14): require('phar://C:/Users...')
#48 {main}
```

## Steps to reproduce the problem

1. juste :  `define($prefix_module_nom, $this->valeur_drapeau_incrementer);` stop progress

## Your environment

* Version used: 3.3.1
* Install method juste PHP in folder with .bat
*  php phpDocumentor.phar -d C:\Users\synxcinaty\PhpstormProjects\Eukaruon -t C:\Users\synxcinaty\PhpstormProjects\Eukaruon\docs/api -vvv
* PHP version 8.0
* Operating system and version Windows 11
* Link to your project:
* Attach code that is involved
* https://github.com/DarkSynx/Eukaruon
* in => modules/[Modules_gestionnaire.php](https://github.com/DarkSynx/Eukaruon/blob/main/modules/Modules_gestionnaire.php) : 163
![image](https://user-images.githubusercontent.com/9467611/181191530-cf528f6b-f177-4d51-9a81-9c8a32c27fd9.png)

**Comment by jaapio** [comment]
I just checked the linked file, This has been resolved, should not be an issue any more in the next release. 

Thanks for reporting this.
