### ISSUE TITLE
No line number shown when having a parse error

### ISSUE THREAD

**Issue by charlesgetup** [phpDocumentor/phpDocumentor#3531]
No line number shown when having a parse error.

## Expected behavior

Shown the line number in the error message.

## Steps to reproduce the problem

1. Run the following command to generate doc. `phpDocumentor -d . -t ../test_doc/ --ignore vendor/ -vvv`
2. Here is the command output. In the **ALERT** line, it said there is **an error was detected**, but no line number provided. And the `Server.php` file content has not be included in the generated document.
```
04:43:07 DEBUG     [app] >> Memory after processing of file: 58.02 megabytes (+0 kilobytes)
04:43:07 NOTICE    [app] Parsing server/http/Server.php
04:43:07 INFO      [app] Starting to parse file: server/http/Server.php
04:43:07 ALERT     [app]   Unable to parse file "server/http/Server.php", an error was detected: A type is missing after a nullable character
04:43:07 NOTICE    [app]   -- Found in phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/type-resolver/src/TypeResolver.php at line 314
04:43:07 DEBUG     [app]   #0 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/type-resolver/src/TypeResolver.php(236): phpDocumentor\Reflection\TypeResolver->parseTypes(Object(ArrayIterator), Object(phpDocumentor\Reflection\Types\Context), 1)
#1 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/type-resolver/src/TypeResolver.php(178): phpDocumentor\Reflection\TypeResolver->parseTypes(Object(ArrayIterator), Object(phpDocumentor\Reflection\Types\Context), 0)
#2 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Param.php(81): phpDocumentor\Reflection\TypeResolver->resolve('?', Object(phpDocumentor\Reflection\Types\Context))
#3 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(218): phpDocumentor\Reflection\DocBlock\Tags\Param::create('$frame\t\tSwoole ...', Object(phpDocumentor\Reflection\TypeResolver), Object(phpDocumentor\Reflection\DocBlock\DescriptionFactory), Object(phpDocumentor\Reflection\Types\Context))
#4 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(149): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('? \t\t\t$frame\t\tSw...', 'param', Object(phpDocumentor\Reflection\Types\Context))
#5 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(245): phpDocumentor\Reflection\DocBlock\StandardTagFactory->create('@param ? \t\t\t$fr...', Object(phpDocumentor\Reflection\Types\Context))
#6 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(105): phpDocumentor\Reflection\DocBlockFactory->parseTagBlock('@param mixed \t\t...', Object(phpDocumentor\Reflection\Types\Context))
#7 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php(78): phpDocumentor\Reflection\DocBlockFactory->create('/**\n\t * Swoole ...', Object(phpDocumentor\Reflection\Types\Context))
#8 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Method.php(65): phpDocumentor\Reflection\Php\Factory\AbstractFactory->createDocBlock(Object(PhpParser\Comment\Doc), Object(phpDocumentor\Reflection\Types\Context))
#9 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php(59): phpDocumentor\Reflection\Php\Factory\Method->doCreate(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\ClassMethod), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#10 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Class_.php(78): phpDocumentor\Reflection\Php\Factory\AbstractFactory->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\ClassMethod), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#11 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php(59): phpDocumentor\Reflection\Php\Factory\Class_->doCreate(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\Class_), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#12 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Namespace_.php(49): phpDocumentor\Reflection\Php\Factory\AbstractFactory->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\Class_), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#13 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/File.php(135): phpDocumentor\Reflection\Php\Factory\Namespace_->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(PhpParser\Node\Stmt\Namespace_), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#14 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/File.php(120): phpDocumentor\Reflection\Php\Factory\File->createElements(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Array, Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#15 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/File.php(71): phpDocumentor\Reflection\Php\Factory\File->createFile(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#16 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Parser/Middleware/ReEncodingMiddleware.php(46): phpDocumentor\Reflection\Php\Factory\File->phpDocumentor\Reflection\Php\Factory\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#17 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\ReEncodingMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#18 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Parser/Middleware/ErrorHandlingMiddleware.php(46): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#19 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\ErrorHandlingMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#20 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Parser/Middleware/CacheMiddleware.php(66): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#21 phar:///usr/local/bin/phpDocumentor/vendor/symfony/cache/Traits/ContractsTrait.php(54): phpDocumentor\Parser\Middleware\CacheMiddleware->phpDocumentor\Parser\Middleware\{closure}(Object(Symfony\Component\Cache\CacheItem), true)
#22 phar:///usr/local/bin/phpDocumentor/vendor/symfony/cache/Traits/ContractsTrait.php(100): Symfony\Component\Cache\Adapter\AbstractAdapter::Symfony\Component\Cache\Traits\{closure}(Object(Closure), Object(Symfony\Component\Cache\CacheItem), true, Object(phpDocumentor\Parser\Cache\FilesystemAdapter), Object(Closure), NULL)
#23 phar:///usr/local/bin/phpDocumentor/vendor/symfony/contracts/Cache/CacheTrait.php(72): Symfony\Component\Cache\Adapter\AbstractAdapter->Symfony\Component\Cache\Traits\{closure}(Object(Symfony\Component\Cache\CacheItem), true)
#24 phar:///usr/local/bin/phpDocumentor/vendor/symfony/cache/Traits/ContractsTrait.php(107): Symfony\Component\Cache\Adapter\AbstractAdapter->contractsGet(Object(phpDocumentor\Parser\Cache\FilesystemAdapter), 'bbc833afdbb7e0e...', Object(Closure), 1.0, Array, NULL)
#25 phar:///usr/local/bin/phpDocumentor/vendor/symfony/contracts/Cache/CacheTrait.php(35): Symfony\Component\Cache\Adapter\AbstractAdapter->doGet(Object(phpDocumentor\Parser\Cache\FilesystemAdapter), 'bbc833afdbb7e0e...', Object(Closure), 1.0, Array)
#26 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Parser/Middleware/CacheMiddleware.php(69): Symfony\Component\Cache\Adapter\AbstractAdapter->get('bbc833afdbb7e0e...', Object(Closure))
#27 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\CacheMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#28 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Parser/Middleware/EmittingMiddleware.php(38): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#29 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\EmittingMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#30 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Parser/Middleware/StopwatchMiddleware.php(50): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#31 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Middleware/ChainFactory.php(43): phpDocumentor\Parser\Middleware\StopwatchMiddleware->execute(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand), Object(Closure))
#32 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/File.php(97): phpDocumentor\Reflection\Middleware\ChainFactory::phpDocumentor\Reflection\Middleware\{closure}(Object(phpDocumentor\Reflection\Php\Factory\File\CreateCommand))
#33 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php(59): phpDocumentor\Reflection\Php\Factory\File->doCreate(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(phpDocumentor\Parser\FlySystemFile), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#34 phar:///usr/local/bin/phpDocumentor/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php(110): phpDocumentor\Reflection\Php\Factory\AbstractFactory->create(Object(phpDocumentor\Reflection\Php\Factory\ContextStack), Object(phpDocumentor\Parser\FlySystemFile), Object(phpDocumentor\Reflection\Php\ProjectFactoryStrategies))
#35 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Parser/Parser.php(205): phpDocumentor\Reflection\Php\ProjectFactory->create('Untitled projec...', Array)
#36 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Pipeline/Stage/Parser/ParseFiles.php(62): phpDocumentor\Parser\Parser->parse(Array)
#37 phar:///usr/local/bin/phpDocumentor/vendor/league/pipeline/src/FingersCrossedProcessor.php(11): phpDocumentor\Pipeline\Stage\Parser\ParseFiles->__invoke(Object(phpDocumentor\Pipeline\Stage\Parser\Payload))
#38 phar:///usr/local/bin/phpDocumentor/vendor/league/pipeline/src/Pipeline.php(34): League\Pipeline\FingersCrossedProcessor->process(Object(phpDocumentor\Pipeline\Stage\Parser\Payload), Object(phpDocumentor\Pipeline\Stage\Parser\TransformToParserPayload), Object(phpDocumentor\Pipeline\Stage\Parser\CollectFiles), Object(phpDocumentor\Pipeline\Stage\Cache\GarbageCollectCache), Object(phpDocumentor\Pipeline\Stage\Cache\LoadProjectDescriptorFromCache), Object(phpDocumentor\Pipeline\Stage\Cache\LoadGuidesFromCache), Object(phpDocumentor\Pipeline\Stage\Parser\ParseFiles), Object(phpDocumentor\Pipeline\Stage\Parser\ParseGuides), Object(phpDocumentor\Pipeline\Stage\Cache\StoreProjectDescriptorToCache), Object(phpDocumentor\Pipeline\Stage\Cache\StoreGuidesToCache))
#39 phar:///usr/local/bin/phpDocumentor/vendor/league/pipeline/src/Pipeline.php(39): League\Pipeline\Pipeline->process(Object(phpDocumentor\Pipeline\Stage\Payload))
#40 phar:///usr/local/bin/phpDocumentor/vendor/league/pipeline/src/FingersCrossedProcessor.php(11): League\Pipeline\Pipeline->__invoke(Object(phpDocumentor\Pipeline\Stage\Payload))
#41 phar:///usr/local/bin/phpDocumentor/vendor/league/pipeline/src/Pipeline.php(34): League\Pipeline\FingersCrossedProcessor->process(Object(phpDocumentor\Pipeline\Stage\Payload), Object(League\Pipeline\Pipeline), Object(League\Pipeline\Pipeline), Object(League\Pipeline\Pipeline), Object(League\Pipeline\Pipeline))
#42 phar:///usr/local/bin/phpDocumentor/vendor/league/pipeline/src/Pipeline.php(39): League\Pipeline\Pipeline->process(Array)
#43 phar:///usr/local/bin/phpDocumentor/src/phpDocumentor/Console/Command/Project/RunCommand.php(290): League\Pipeline\Pipeline->__invoke(Array)
#44 phar:///usr/local/bin/phpDocumentor/vendor/symfony/console/Command/Command.php(298): phpDocumentor\Console\Command\Project\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 phar:///usr/local/bin/phpDocumentor/vendor/symfony/console/Application.php(1033): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 phar:///usr/local/bin/phpDocumentor/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(phpDocumentor\Console\Command\Project\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 phar:///usr/local/bin/phpDocumentor/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(phpDocumentor\Console\Command\Project\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 phar:///usr/local/bin/phpDocumentor/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 phar:///usr/local/bin/phpDocumentor/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 phar:///usr/local/bin/phpDocumentor/bin/phpdoc(43): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#51 /usr/local/bin/phpDocumentor(14): require('phar:///usr/loc...')
#52 {main}
04:43:07 DEBUG     [app] >> Memory after processing of file: 62.02 megabytes (+4,096 kilobytes)
```
 
3. Here is the short output of the same command without verbose option. Still no line number shown.
```
Parsing files
  48/159 [========>-------------------]  30%04:28:01 ALERT     [app]   Unable to parse file "server/http/Server.php", an error was detected: A type is missing after a nullable character
 159/159 [============================] 100%
Applying transformations (can take a while)
 21/21 [============================] 100%
All done in 12 seconds!
```

## Your environment

* Version used: v3.3.1
* Install method: Downloaded the phar file from GitHub
* PHP version: 8.1.18
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): alpine3.17 (The project has been built based on this docker container, `FROM php:8.1.18-alpine3.17 AS base`)
* Link to your project: Project has not launched yet.
* Attach code that is involved: I could not attach the source code of `server/http/Server.php`. Just need to see line number in error message.

Any help is appreciated. Thanks.

**Comment by charlesgetup** [comment]
I finally found the error I made. See the code below. But I am still happy to see that the line number could be included in the error message. The `server/http/Server.php` file is quite large. And I have not edited that file for a long time. To have the line number in the error message, I am sure that this will help someone, including me.

Error I made: 
```
        /**
	 * xxxxxxx.
	 * 
	 * ....
	 * @param ?	$task		Server task.
	 * ......
	 */
```
